version: '3.8'

services:
  # Neo4j database service
  neo4j:
    image: neo4j:5.7
    container_name: neo4j_db
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt protocol (used by the NestJS app)
    environment:
      - NEO4J_AUTH=neo4j/test_password  # Set your username/password
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_connector_http_advertised__address=:7474
    volumes:
      - neo4j_data:/data  # Persist Neo4j data

  # NestJS application service
  llm-knowledge-graph:
    build:
      context: ./  # Assuming Dockerfile for NestJS is in the root directory
    container_name: llm-knowledge-graph
    ports:
      - "3000:3000"  # Expose NestJS app port
    depends_on:
      - neo4j
    environment:
      - NEO4J_URL=bolt://neo4j_db:7687  # Neo4j service address
      - NEO4J_USERNAME=neo4j  # Neo4j username
      - NEO4J_PASSWORD=test_password  # Neo4j password
    networks:
      - app-network

# Define a shared network for communication between containers
networks:
  app-network:
    driver: bridge

# Volumes to persist Neo4j data
volumes:
  neo4j_data:
